version: '2'

services:

  app:
    container_name: tariff.app
    build: docker/php
    volumes:
      - .:/var/www
      - ./docker/php/composer:/opt/composer

  nginx:
    container_name: tariff.nginx
    build: docker/nginx
    volumes_from:
      - app
    ports:
      - 835:80

  postgresql:
    container_name: tariff.postgresql
    image: postgres
    volumes:
      - ./docker/postgresql/.db:/var/lib/postgresql/data:rw
    env_file:
      - ./docker/postgresql/env
    ports:
      - 851:5432
